// Generated by gencpp from file midterm_project/Weather.msg
// DO NOT EDIT!


#ifndef MIDTERM_PROJECT_MESSAGE_WEATHER_H
#define MIDTERM_PROJECT_MESSAGE_WEATHER_H

#include <ros/service_traits.h>


#include <midterm_project/WeatherRequest.h>
#include <midterm_project/WeatherResponse.h>


namespace midterm_project
{

struct Weather
{

typedef WeatherRequest Request;
typedef WeatherResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Weather
} // namespace midterm_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::midterm_project::Weather > {
  static const char* value()
  {
    return "204ae4bdd15d2eba6c7e323a2fe04a4e";
  }

  static const char* value(const ::midterm_project::Weather&) { return value(); }
};

template<>
struct DataType< ::midterm_project::Weather > {
  static const char* value()
  {
    return "midterm_project/Weather";
  }

  static const char* value(const ::midterm_project::Weather&) { return value(); }
};


// service_traits::MD5Sum< ::midterm_project::WeatherRequest> should match
// service_traits::MD5Sum< ::midterm_project::Weather >
template<>
struct MD5Sum< ::midterm_project::WeatherRequest>
{
  static const char* value()
  {
    return MD5Sum< ::midterm_project::Weather >::value();
  }
  static const char* value(const ::midterm_project::WeatherRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::midterm_project::WeatherRequest> should match
// service_traits::DataType< ::midterm_project::Weather >
template<>
struct DataType< ::midterm_project::WeatherRequest>
{
  static const char* value()
  {
    return DataType< ::midterm_project::Weather >::value();
  }
  static const char* value(const ::midterm_project::WeatherRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::midterm_project::WeatherResponse> should match
// service_traits::MD5Sum< ::midterm_project::Weather >
template<>
struct MD5Sum< ::midterm_project::WeatherResponse>
{
  static const char* value()
  {
    return MD5Sum< ::midterm_project::Weather >::value();
  }
  static const char* value(const ::midterm_project::WeatherResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::midterm_project::WeatherResponse> should match
// service_traits::DataType< ::midterm_project::Weather >
template<>
struct DataType< ::midterm_project::WeatherResponse>
{
  static const char* value()
  {
    return DataType< ::midterm_project::Weather >::value();
  }
  static const char* value(const ::midterm_project::WeatherResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIDTERM_PROJECT_MESSAGE_WEATHER_H
